title: Energiekostenpauschale für Unternehmen
author: Österreichische Forschungsförderungsgesellschaft
email: foerderservice@ffg.at

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Hier entsteht die Website für die Energiekostenpauschale, eine Förderung für Kleinst- und Kleinunternehmen der
  Österreichischen Forschungsförderungsgesellschaft im Auftrag des
  Bundesministeriums für Arbeit und Wirtschaft

# Build settings
lang: de
theme: minima

#remote_theme: amitmerchant1990/reverie
#remote_theme: emilbaehr/automatic-app-landing-page
#remote_theme: pages-themes/minimal@v0.2.0
#remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-seo-tag
  #- jekyll-feed
  #- jekyll-remote-theme # add this line to the plugins list if you already have one

# Theme-specific settings
#show_downloads: false
#github:
#  is_project_page: false

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - {
        platform: facebook,
        user_url: "https://www.facebook.com/FFG.ForschungWirkt/",
      }
    #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
    #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
    #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
    #   - { platform: github,         user_url: "https://github.com/jekyll/minima" }
    #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
    #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
    #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/company/ffg" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - index.md
  - interesse2.md
  - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false

collections:
  sections:
    output: false

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
timezone: Europe/Vienna
